# This is an empty template playbook
# You can write your custom configuration here

- name: disable qxl
  hosts:
    - routers
    - hosts
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: disable qxl
      include_role:
        name: disable-qxl
      when: ansible_os_family == 'Debian'


- name: user access
  hosts:
    - user_accessible_nodes
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: kypo-user-access
      kypo_user_access_password: 'kypo'

- name: Flush ALL rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: "flush all iptables rules"
      ansible.builtin.iptables:
        flush: yes

- name: Setup DROP rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: setup
      ansible.builtin.iptables:
          chain: FORWARD
          destination: '{{ private_ip_address_range }}'
          in_interface: eth2
          out_interface: eth0
          jump: DROP
      loop:
         - 10.0.0.0/8
         - 172.16.0.0/12
         - 224.0.0.0/4


