# This is an empty template playbook
# You can write your custom configuration here

- name: disable qxl
  hosts:
    - routers
    - hosts
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: disable qxl
      include_role:
        name: disable-qxl
      when: ansible_os_family == 'Debian'


- name: user access
  hosts:
    - user_accessible_nodes
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: kypo-user-access
      kypo_user_access_password: 'kypo'

- name: Flush ALL rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: "flush all iptables rules"
      iptables:
        flush: yes

- name: Setup DROP rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - set_fact:
        private_ip_address_range: ['10.0.0.0/8', '172.16.0.0/12', '224.0.0.0/4']
    - name: setup
      vars:
        iptables_rules:
          - chain: FORWARD
            destination: '{{ item }}'
            in_interface: eth2
            out_interface: eth0
            jump: DROP
      loop: '{{ private_ip_address_range }}'


